export const EVENTS = {
	DRAW_CARD: 'DRAW_CARD',
	PLAYER_ON_TURN: 'PLAYER_ON_TURN',
	PLAY_CARD: 'PLAY_CARD',
	SET_BRISCOLA: 'SET_BRISCOLA',
	HAND_FINISHED: 'HAND_FINISHED',
	GAME_OVER: 'GAME_OVER',
	PLAYER_READY: 'PLAYER_READY'
};
